
--- --- ---

DROP TABLE IF EXISTS _COURSE;

CREATE TABLE IF NOT EXISTS _COURSE(
  _COURSE_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  _COURSE_CREATED_AT DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  _COURSE_UPDATED_AT DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  _COURSE_PASSCODE UUID NOT NULL DEFAULT gen_random_uuid(),
  _COURSE_ADMIN_STATUS VARCHAR(255) NOT NULL,
  _COURSE_LANGUAGES VARCHAR(100) NOT NULL,
  _COURSE_SUBJECT VARCHAR(30) NOT NULL,
  _COURSE_QUESTION_IDS VARCHAR(255) NOT NULL,
  _COURSE_COMPLETE BOOLEAN NOT NULL,
  _COURSE_POINTS INT NOT NULL
);

--- --- ---

DROP TABLE IF EXISTS _QUESTIONS;

CREATE TABLE IF NOT EXISTS _QUESTIONS(
  _QUESTION_CREATED_AT DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  _QUESTION_UPDATED_AT DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  _QUESTION_ID VARCHAR(30) PRIMARY KEY,
  _QUESTION_LANGUAGE VARCHAR(30) NOT NULL,
  _QUESTION_LEVEL INT NOT NULL,
  _QUESTION_POINTS INT NOT NULL,
  _QUESTION_TASK VARCHAR(255) NOT NULL,
  _QUESTION_DATA VARCHAR(255) NOT NULL,
  _QUESTION_ANSWER_REGEX VARCHAR(255) NOT NULL,
  _QUESTION_RESULT VARCHAR(255) NOT NULL,
  _QUESTION_HINTS VARCHAR(255) NOT NULL,
  _QUESTION_BOILERPLATE VARCHAR(255) NOT NULL,
  _QUESTION_CONDITIONS VARCHAR(255) NOT NULL,
  _QUESTION_CONSTRAINTS VARCHAR(255) NOT NULL,
  _QUESTION_CATEGORY VARCHAR(155) NOT NULL,
  _QUESTION_CATEGORY_SUB VARCHAR(155) NOT NULL,
  _QUESTION_TAGS VARCHAR(255) NOT NULL,
  _QUESTION_REFS VARCHAR(255) NOT NULL
);
