CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS _USER(
  _USER_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  _USER_CREATED_AT DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  _USER_UPDATED_AT DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  _USER_PASSCODE UUID NOT NULL DEFAULT gen_random_uuid(),
  _USER_EMAIL VARCHAR(50) UNIQUE NOT NULL,
  _USER_PASSWORD VARCHAR(30) NOT NULL,
  _USER_FIRST_NAME VARCHAR(30) NOT NULL,
  _USER_LAST_NAME VARCHAR(30) NOT NULL,
  _USER_DEFAULT_LANGUAGE VARCHAR(30) NOT NULL,
  _USER_DEFAULT_ROUTE VARCHAR(50) NOT NULL,
  _USER_POINTS INT NOT NULL,
  _USER_COURSES VARCHAR(255) NOT NULL,
);

CREATE TABLE IF NOT EXISTS _STUDENT(
  _STUDENT_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  _STUDENT_CREATED_AT DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  _STUDENT_UPDATED_AT DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  _STUDENT_PASSCODE UUID NOT NULL DEFAULT gen_random_uuid(),
  _STUDENT_ADMIN_STATUS BOOLEAN NOT NULL DEFAULT FALSE,
  _STUDENT_POINTS INT NOT NULL,
  _STUDENT_COURSES VARCHAR(255) NOT NULL,
  _USER_ID UUID NOT NULL,
  _USER_EMAIL VARCHAR(50) UNIQUE NOT NULL,
  _USER_COURSES VARCHAR(255),
  CONSTRAINT fk_user
    FOREIGN KEY(_USER_ID)
	  REFERENCES _USER(_USER_ID),
  CONSTRAINT fk_user_email
    FOREIGN KEY(_USER_EMAIL)
    REFERENCES _USER(_USER_EMAIL),
  CONSTRAINT fk_user_courses
    FOREIGN KEY(_USER_COURSES)
	  REFERENCES _USER(_USER_COURSES),
);

CREATE TABLE IF NOT EXISTS _ADMIN(
  _ADMIN_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  _ADMIN_CREATED_AT DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  _ADMIN_UPDATED_AT DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  _ADMIN_PASSCODE UUID NOT NULL DEFAULT gen_random_uuid(),
  _ADMIN_STATUS BOOLEAN NOT NULL DEFAULT TRUE,
  _ADMIN_POINTS INT NOT NULL,
  _ADMIN_COURSES VARCHAR(255) NOT NULL,
  _USER_ID UUID NOT NULL,
  _USER_EMAIL VARCHAR(50) UNIQUE NOT NULL,
  _USER_COURSES VARCHAR(255),
  CONSTRAINT fk_user
    FOREIGN KEY(_USER_ID)
	  REFERENCES _USER(_USER_ID),
  CONSTRAINT fk_user_email
    FOREIGN KEY(_USER_EMAIL),
    REFERENCES _USER(_USER_EMAIL)
  CONSTRAINT fk_user_courses
    FOREIGN KEY(_USER_COURSES)
	  REFERENCES _USER(_USER_COURSES),
);

CREATE TABLE IF NOT EXISTS _COURSE(
  _COURSE_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  _COURSE_CREATED_AT DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  _COURSE_UPDATED_AT DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  _COURSE_PASSCODE UUID NOT NULL DEFAULT gen_random_uuid(),
  _COURSE_ADMIN_STATUS VARCHAR(255) NOT NULL,
  _COURSE_LANGUAGES VARCHAR(100) NOT NULL,
  _COURSE_SUBJECT VARCHAR(30) NOT NULL,
  _COURSE_ITEMS VARCHAR(255) NOT NULL,
  _COURSE_COMPLETE BOOLEAN NOT NULL,
  _COURSE_POINTS INT NOT NULL,
);

CREATE TABLE IF NOT EXISTS _QUESTIONS(
  _QUESTION_CREATED_AT DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  _QUESTION_UPDATED_AT DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  _QUESTION_ID VARCHAR(30) PRIMARY KEY,
  _QUESTION_LANGUAGE VARCHAR(30) NOT NULL,
  _QUESTION_LEVEL INT NOT NULL,
  _QUESTION_POINTS INT NOT NULL,
  _QUESTION_TASK VARCHAR(255) NOT NULL,
  _QUESTION_DATA VARCHAR(255) NOT NULL,
  _QUESTION_RESULT VARCHAR(255) NOT NULL,
  _QUESTION_HINTS VARCHAR(255) NOT NULL,
  _QUESTION_BOILERPLATE VARCHAR(255) NOT NULL,
  _QUESTION_CONDITIONS VARCHAR(255) NOT NULL,
  _QUESTION_CONSTRAINTS VARCHAR(255) NOT NULL,
  _QUESTION_CATEGORY VARCHAR(155) NOT NULL,
  _QUESTION_CATEGORY_SUB VARCHAR(155) NOT NULL,
  _QUESTION_TAGS VARCHAR(255) NOT NULL,
  _QUESTION_REFS VARCHAR(255) NOT NULL,
);
