CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

--- --- ---

/**
CREATE TABLE IF NOT EXISTS _USER( _USER_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(), _USER_UPDATED_AT DATE NOT NULL DEFAULT CURRENT_TIMESTAMP, _USER_GUEST BOOLEAN NOT NULL DEFAULT false, _USER_ADMIN BOOLEAN NOT NULL DEFAULT false, _USER_SUBSCRIPTION Int NOT NULL DEFAULT 001001002, _USER_IP_ADDRESS VARCHAR(50) NOT NULL, _USER_PASSCODE UUID NOT NULL DEFAULT gen_random_uuid(),  _USER_PASSCODE_CONFIRMED BOOLEAN NOT NULL DEFAULT false, _USER_EMAIL VARCHAR(50) UNIQUE NOT NULL, _USER_EMAIL_CONFIRMED BOOLEAN NOT NULL DEFAULT false, _USER_PASSWORD VARCHAR(30) NOT NULL, _USER_USERNAME VARCHAR(30) NOT NULL, _USER_FIRST_NAME VARCHAR(30) NOT NULL, _USER_LAST_NAME VARCHAR(30) NOT NULL, _USER_SOCIAL_HANDLE_GITHUB VARCHAR(30) NOT NULL, _USER_SOCIAL_HANDLE_GOOGLE VARCHAR(30) NOT NULL, _USER_SOCIAL_HANDLE_APPLE VARCHAR(30) NOT NULL, _USER_SOCIAL_HANDLE_FACEBOOK VARCHAR(30) NOT NULL, _USER_SOCIAL_HANDLE_TWITTER VARCHAR(30) NOT NULL,  _USER_DEFAULT_LANGUAGE VARCHAR(30) NOT NULL, _USER_DEFAULT_ROUTE VARCHAR(50) NOT NULL, _USER_POINTS INT NOT NULL, _USER_COURSES VARCHAR(255) NOT NULL);
*/
DROP TABLE IF EXISTS _USER;

CREATE TABLE IF NOT EXISTS _USER(
  _USER_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  _USER_CREATED_AT DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  _USER_UPDATED_AT DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  _USER_GUEST BOOLEAN NOT NULL DEFAULT false,
  _USER_ADMIN BOOLEAN NOT NULL DEFAULT false,
  _USER_SUBSCRIPTION Int NOT NULL DEFAULT 001001002,
  _USER_IP_ADDRESS VARCHAR(50) NOT NULL,
  _USER_PASSCODE UUID NOT NULL DEFAULT gen_random_uuid(),
  _USER_PASSCODE_CONFIRMED BOOLEAN NOT NULL DEFAULT false,
  _USER_EMAIL VARCHAR(50) UNIQUE NOT NULL,
  _USER_EMAIL_CONFIRMED BOOLEAN NOT NULL DEFAULT false,
  _USER_EMAIL_PASSCODE UUID NOT NULL DEFAULT gen_random_uuid(),
  _USER_PASSWORD VARCHAR(30) NOT NULL,
  _USER_USERNAME VARCHAR(30) NOT NULL,
  _USER_FIRST_NAME VARCHAR(30) NOT NULL,
  _USER_LAST_NAME VARCHAR(30) NOT NULL,
  _USER_SOCIAL_HANDLE_GITHUB VARCHAR(30) NOT NULL,
  _USER_SOCIAL_HANDLE_GOOGLE VARCHAR(30) NOT NULL,
  _USER_SOCIAL_HANDLE_APPLE VARCHAR(30) NOT NULL,
  _USER_SOCIAL_HANDLE_FACEBOOK VARCHAR(30) NOT NULL,
  _USER_SOCIAL_HANDLE_TWITTER VARCHAR(30) NOT NULL,
  _USER_SOCIAL_HANDLE_LINKEDIN VARCHAR(30) NOT NULL,
  _USER_DEFAULT_LANGUAGE VARCHAR(30) NOT NULL,
  _USER_DEFAULT_ROUTE VARCHAR(50) NOT NULL,
  _USER_POINTS_TOTAL INT NOT NULL,
  _USER_COURSES VARCHAR(255) NOT NULL
);

--- --- ---

DROP TABLE IF EXISTS _USER_POINTS;

CREATE TABLE IF NOT EXISTS _USER_POINTS(
  _USER_POINTS_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  _USER_POINTS_CREATED_AT DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  _USER_POINTS_UPDATED_AT DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  _USER_POINTS_TOTAL INT NOT NULL,
  _USER_POINTS_JAVASCRIPT INT NOT NULL,
  _USER_POINTS_JAVA INT NOT NULL,
  _USER_POINTS_PYTHON INT NOT NULL,
  _USER_ID UUID NOT NULL,
  CONSTRAINT fk_user
    FOREIGN KEY(_USER_ID)
	  REFERENCES _USER(_USER_ID),
);

--- --- ---

DROP TABLE IF EXISTS _USER_POINTS_JAVASCRIPT;

CREATE TABLE IF NOT EXISTS _USER_POINTS_JAVASCRIPT(
  _USER_JAVASCRIPT_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  _USER_JAVASCRIPT_CREATED_AT DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  _USER_JAVASCRIPT_UPDATED_AT DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  _USER_JAVASCRIPT_TOTAL INT NOT NULL,
  _USER_JAVASCRIPT_COMMENTS INT NOT NULL,
  _USER_JAVASCRIPT_VARIABLES INT NOT NULL,
  _USER_JAVASCRIPT_ARRAYS INT NOT NULL,
  _USER_JAVASCRIPT_OBJECTS INT NOT NULL,
  _USER_JAVASCRIPT_FUNCTIONS INT NOT NULL,
  _USER_ID UUID NOT NULL,
  CONSTRAINT fk_user
    FOREIGN KEY(_USER_ID)
	  REFERENCES _USER(_USER_ID),
);

--- --- ---

DROP TABLE IF EXISTS _USER_POINTS_JAVA;

CREATE TABLE IF NOT EXISTS _USER_POINTS_JAVA(
  _USER_JAVA_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  _USER_JAVA_CREATED_AT DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  _USER_JAVA_UPDATED_AT DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  _USER_JAVA_TOTAL INT NOT NULL,
  _USER_JAVA_COMMENTS INT NOT NULL,
  _USER_JAVA_VARIABLES INT NOT NULL,
  _USER_JAVA_ARRAYS INT NOT NULL,
  _USER_JAVA_OBJECTS INT NOT NULL,
  _USER_JAVA_FUNCTIONS INT NOT NULL,
  _USER_ID UUID NOT NULL,
  CONSTRAINT fk_user
    FOREIGN KEY(_USER_ID)
	  REFERENCES _USER(_USER_ID),
);

--- --- ---

DROP TABLE IF EXISTS _USER_POINTS_PYTHON;

CREATE TABLE IF NOT EXISTS _USER_POINTS_PYTHON(
  _USER_PYTHON_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  _USER_PYTHON_CREATED_AT DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  _USER_PYTHON_UPDATED_AT DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  _USER_PYTHON_TOTAL INT NOT NULL,
  _USER_PYTHON_COMMENTS INT NOT NULL,
  _USER_PYTHON_VARIABLES INT NOT NULL,
  _USER_PYTHON_ARRAYS INT NOT NULL,
  _USER_PYTHON_OBJECTS INT NOT NULL,
  _USER_PYTHON_FUNCTIONS INT NOT NULL,
  _USER_ID UUID NOT NULL,
  CONSTRAINT fk_user
    FOREIGN KEY(_USER_ID)
	  REFERENCES _USER(_USER_ID),
);

--- --- ---

/**
CREATE TABLE IF NOT EXISTS _GUEST(_GUEST_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(), _GUEST_CREATED_AT DATE NOT NULL DEFAULT CURRENT_TIMESTAMP, _GUEST_UPDATED_AT DATE NOT NULL DEFAULT CURRENT_TIMESTAMP, _GUEST_ACCESS_TOKEN VARCHAR(100) NOT NULL, _GUEST_FIRST_LOGIN BOOLEAN NOT NULL DEFAULT false, _GUEST_ADMIN BOOLEAN NOT NULL DEFAULT false, _GUEST_SUBSCRIPTION VARCHAR(50) NOT NULL DEFAULT "1234, guest", _GUEST_IP_ADDRESS VARCHAR(50) NOT NULL, _GUEST_PASSCODE UUID NOT NULL DEFAULT gen_random_uuid(), _GUEST_PASSCODE_CONFIRMED BOOLEAN NOT NULL DEFAULT false, _GUEST_EMAIL VARCHAR(50) UNIQUE NOT NULL, _GUEST_EMAIL_CONFIRMED BOOLEAN NOT NULL DEFAULT false, _GUEST_PASSWORD VARCHAR(35) NOT NULL,_GUEST_DEFAULT_LANGUAGE VARCHAR(30) NOT NULL, _GUEST_DEFAULT_ROUTE VARCHAR(50) NOT NULL, _GUEST_POINTS_TOTAL INT NOT NULL, _GUEST_POINTS_JAVASCRIPT INT NOT NULL, _GUEST_POINTS_JAVA INT NOT NULL, _GUEST_POINTS_PYTHON INT NOT NULL, _GUEST_COURSES VARCHAR(255) NOT NULL);
*/

DROP TABLE IF EXISTS _GUEST;

CREATE TABLE IF NOT EXISTS _GUEST(
  _GUEST_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  _GUEST_CREATED_AT DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  _GUEST_UPDATED_AT DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  _GUEST_ACCESS_TOKEN VARCHAR(100) NOT NULL,
  _GUEST_FIRST_LOGIN BOOLEAN NOT NULL DEFAULT false,
  _GUEST_ADMIN BOOLEAN NOT NULL DEFAULT false,
  _GUEST_SUBSCRIPTION VARCHAR(50) NOT NULL,
  _GUEST_IP_ADDRESS VARCHAR(50) NOT NULL,
  _GUEST_PASSCODE UUID NOT NULL DEFAULT gen_random_uuid(),
  _GUEST_PASSCODE_CONFIRMED BOOLEAN NOT NULL DEFAULT false,
  _GUEST_EMAIL VARCHAR(50) UNIQUE NOT NULL,
  _GUEST_EMAIL_CONFIRMED BOOLEAN NOT NULL DEFAULT false,
  _GUEST_EMAIL_PASSCODE UUID NOT NULL DEFAULT gen_random_uuid(),
  _GUEST_PASSWORD VARCHAR(100) NOT NULL,
  _GUEST_DEFAULT_LANGUAGE VARCHAR(30) NOT NULL,
  _GUEST_DEFAULT_ROUTE VARCHAR(50) NOT NULL,
  _GUEST_POINTS_TOTAL INT NOT NULL,
  _GUEST_POINTS_JAVASCRIPT INT NOT NULL,
  _GUEST_POINTS_JAVA INT NOT NULL,
  _GUEST_POINTS_PYTHON INT NOT NULL,
  _GUEST_COURSES VARCHAR(255) NOT NULL
);

--- --- ---

DROP TABLE IF EXISTS _STUDENT;

CREATE TABLE IF NOT EXISTS _STUDENT(
  _STUDENT_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  _STUDENT_CREATED_AT DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  _STUDENT_UPDATED_AT DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  _STUDENT_PASSCODE UUID NOT NULL DEFAULT gen_random_uuid(),
  _STUDENT_PASSCODE_CONFIRMED BOOLEAN NOT NULL DEFAULT false,
  _STUDENT_ADMIN_STATUS BOOLEAN NOT NULL DEFAULT FALSE,
  _STUDENT_POINTS INT NOT NULL,
  _STUDENT_COURSES VARCHAR(255) NOT NULL,
  _USER_ID UUID NOT NULL,
  _USER_EMAIL VARCHAR(50) UNIQUE NOT NULL,
  _USER_COURSES VARCHAR(255),
  CONSTRAINT fk_user
    FOREIGN KEY(_USER_ID)
	  REFERENCES _USER(_USER_ID),
  CONSTRAINT fk_user_email
    FOREIGN KEY(_USER_EMAIL)
    REFERENCES _USER(_USER_EMAIL),
  CONSTRAINT fk_user_courses
    FOREIGN KEY(_USER_COURSES)
	  REFERENCES _USER(_USER_COURSES)
);

--- --- ---

DROP TABLE IF EXISTS _ADMIN;

CREATE TABLE IF NOT EXISTS _ADMIN(
  _ADMIN_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  _ADMIN_CREATED_AT DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  _ADMIN_UPDATED_AT DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  _ADMIN_PASSCODE UUID NOT NULL DEFAULT gen_random_uuid(),
  _ADMIN_PASSCODE_CONFIRMED BOOLEAN NOT NULL DEFAULT false,
  _ADMIN_STATUS BOOLEAN NOT NULL DEFAULT TRUE,
  _ADMIN_POINTS INT NOT NULL,
  _ADMIN_COURSES VARCHAR(255) NOT NULL,
  _USER_ID UUID NOT NULL,
  _USER_EMAIL VARCHAR(50) UNIQUE NOT NULL,
  _USER_COURSES VARCHAR(255),
  CONSTRAINT fk_user
    FOREIGN KEY(_USER_ID)
	  REFERENCES _USER(_USER_ID),
  CONSTRAINT fk_user_email
    FOREIGN KEY(_USER_EMAIL),
    REFERENCES _USER(_USER_EMAIL)
  CONSTRAINT fk_user_courses
    FOREIGN KEY(_USER_COURSES)
	  REFERENCES _USER(_USER_COURSES)
);

--- --- ---

DROP TABLE IF EXISTS _COURSE;

CREATE TABLE IF NOT EXISTS _COURSE(
  _COURSE_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  _COURSE_CREATED_AT DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  _COURSE_UPDATED_AT DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  _COURSE_PASSCODE UUID NOT NULL DEFAULT gen_random_uuid(),
  _COURSE_ADMIN_STATUS VARCHAR(255) NOT NULL,
  _COURSE_LANGUAGES VARCHAR(100) NOT NULL,
  _COURSE_SUBJECT VARCHAR(30) NOT NULL,
  _COURSE_QUESTION_IDS VARCHAR(255) NOT NULL,
  _COURSE_COMPLETE BOOLEAN NOT NULL,
  _COURSE_POINTS INT NOT NULL
);

--- --- ---

DROP TABLE IF EXISTS _QUESTIONS;

CREATE TABLE IF NOT EXISTS _QUESTIONS(
  _QUESTION_CREATED_AT DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  _QUESTION_UPDATED_AT DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  _QUESTION_ID VARCHAR(30) PRIMARY KEY,
  _QUESTION_LANGUAGE VARCHAR(30) NOT NULL,
  _QUESTION_LEVEL INT NOT NULL,
  _QUESTION_POINTS INT NOT NULL,
  _QUESTION_TASK VARCHAR(255) NOT NULL,
  _QUESTION_DATA VARCHAR(255) NOT NULL,
  _QUESTION_RESULT VARCHAR(255) NOT NULL,
  _QUESTION_HINTS VARCHAR(255) NOT NULL,
  _QUESTION_BOILERPLATE VARCHAR(255) NOT NULL,
  _QUESTION_CONDITIONS VARCHAR(255) NOT NULL,
  _QUESTION_CONSTRAINTS VARCHAR(255) NOT NULL,
  _QUESTION_CATEGORY VARCHAR(155) NOT NULL,
  _QUESTION_CATEGORY_SUB VARCHAR(155) NOT NULL,
  _QUESTION_TAGS VARCHAR(255) NOT NULL,
  _QUESTION_REFS VARCHAR(255) NOT NULL
);
